### ISSUE TITLE
This transaction has already been marked as authorized

### ISSUE THREAD

**Issue by MisinformedDNA** [spree-contrib/spree_tax_cloud#21]
I just updated to Spree tag v2.4.3 and am getting an error when placing an order, specifically when transitioning from confirm to complete.

You can repro this by running [this walkthrough](https://github.com/spree-contrib/spree_api_examples/blob/master/examples/checkout/walkthrough.rb). In the logs you will see

```
Problem:
  This transaction has already been marked as authorized (CartID : R487222301)
Summary:
  The TaxCloud server returned an error in the response: `{:authorized_with_capture_response=>{:authorized_with_capture_result=>{:response_type=>"Error", :messages=>{:response_message=>{:response_type=>"Error", :message=>"This transactio
n has already been marked as authorized (CartID : R487222301)"}}}, :@xmlns=>"http://taxcloud.net"}}`
Resolution:
  Check the request parameters.
```

Any ideas?

**Comment by brchristian** [comment]
Hmm! I haven't been using Spree 2.4 at all, so I'm not aware personally of what might have changed. Perhaps @JDutil can weigh in. @MisinformedDNA could I trouble you for a stack trace?

**Comment by MisinformedDNA** [comment]
```
Problem:
  This transaction has already been marked as authorized (CartID : R762715182)
Summary:
  The TaxCloud server returned an error in the response: `{:authorized_with_capture_response=>{:authorized_with_capture_result=>{:response_type=>"Error", :messages=>{:response_message=>{:response_type=>"Error", :message=>"This transaction has already been marked as authorized (CartID : R762715182)"}}}, :@xmlns=>"http://taxcloud.net"}}`
Resolution:
  Check the request parameters.
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tax_cloud-0.3.0/lib/tax_cloud/responses/base.rb:79:in `parse!'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tax_cloud-0.3.0/lib/tax_cloud/responses/base.rb:12:in `initialize'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tax_cloud-0.3.0/lib/tax_cloud/responses/generic.rb:25:in `new'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tax_cloud-0.3.0/lib/tax_cloud/responses/generic.rb:25:in `parse'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/tax_cloud-0.3.0/lib/tax_cloud/transaction.rb:93:in `authorized_with_capture'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree_tax_cloud-989cb96a9556/app/models/spree/order_decorator.rb:11:in `capture_tax_cloud'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/eval_helpers.rb:58:in `evaluate_method'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/callback.rb:191:in `block in run_methods'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `each'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `run_methods'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/callback.rb:159:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block (2 levels) in after'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `each'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block in after'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `catch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `after'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:251:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:127:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:182:in `block in within_transaction'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:227:in `block in within_transaction'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:1904:in `within_transaction'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:226:in `within_transaction'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:181:in `within_transaction'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/transition.rb:219:in `perform'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/event.rb:172:in `fire'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/event.rb:247:in `block in add_actions'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/event.rb:252:in `block in add_actions'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree-d7967de5bf4f/api/app/controllers/spree/api/checkouts_controller.rb:14:in `next'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:136:in `process'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionview-4.1.8/lib/action_view/rendering.rb:30:in `process'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:196:in `dispatch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:232:in `block in action'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/error_collector.rb:50:in `traced_call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/migration.rb:380:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
  Rendered text template (0.5ms)
Completed 422 Unprocessable Entity in 8257ms (Views: 2.1ms | ActiveRecord: 118.0ms)
```

**Comment by JDutil** [comment]
I'm wasn't able to reproduce this at all on my setup w/latest 2-4-stable so I don't think this has anything to do between 2.4.2 to 2.4.3.  The error is saying the transaction has already been authorized with tax cloud so I assume it's related to a double submission somehow.

**Comment by MisinformedDNA** [comment]
I just tested this again. It is succeeding in development, but failing in staging (rails_env = production). Maybe the error only occurs in production where TaxCloud takes authorizations more critically? I'm running code from spree_api_examples (see OP), so if there is a double submission, Spree would have to be doing it.
